config/routes.rb
Rails.application.routes.draw do
  root 'jobs#index'
  resources :job_components
  resources :jobs
  resources :customers
  resources :components
  resources :employees
  resources :statuses
  resources :stages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :employee
  belongs_to :customer
  belongs_to :stage
  belongs_to :status
  has_many :job_components
  has_many :components, through: :job_components

  validates :name, :employee_id, :customer_id, :stage_id, :status_id, presence: true
  after_save :complete_math

  def complete_math
    subtotalZ = self.job_components.joins(:component).sum(:price)
    taxE = 0.034
    markup = 0.1
    multiY = subtotalZ * taxE
    multiZ = subtotalZ * markup
    c = subtotalZ + multiY + multiZ
    update_columns(subtotal:subtotalZ, total: c)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :employee_id, :customer_id, :stage_id, :status_id)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :job_name %>
  </div>

  <div class="field">
    <%= form.label :employee_id %>
    <%= form.collection_select :employee_id, Employee.all,  :id, :name %>
  </div>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.collection_select :customer_id, Customer.all,  :id, :name %>
  </div>

  <div class="field">
    <%= form.label :stage_id %>
    <%= form.collection_select :stage_id, Stage.all,  :id, :name %>
  </div>

  <div class="field">
    <%= form.label :status_id %>
    <%= form.collection_select :status_id, Status.all,  :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Employee</th>
      <th>Customer</th>
      <th>Stage</th>
      <th>Status</th>
      <th>Subtotal</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.name %></td>
        <td><%= job.employee.name %></td>
        <td><%= job.customer.name %></td>
        <td><%= job.stage.name %></td>
        <td><%= job.status.name %></td>
        <td><%= job.subtotal %></td>
        <td><%= job.total %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @job.name %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @job.employee.name %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @job.customer.name %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @job.stage.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @job.status.name %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>