config/routes.rb
Rails.application.routes.draw do
  root 'jobs#index'
  resources :job_components
  resources :jobs
  resources :customers
  resources :components
  resources :employees
  resources :statuses
  resources :stages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/stage.rb
class Stage < ApplicationRecord
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  before_action :set_stage, only: [:show, :edit, :update, :destroy]

  # GET /stages
  # GET /stages.json
  def index
    @stages = Stage.all
  end

  # GET /stages/1
  # GET /stages/1.json
  def show
  end

  # GET /stages/new
  def new
    @stage = Stage.new
  end

  # GET /stages/1/edit
  def edit
  end

  # POST /stages
  # POST /stages.json
  def create
    @stage = Stage.new(stage_params)

    respond_to do |format|
      if @stage.save
        format.html { redirect_to @stage, notice: 'Stage was successfully created.' }
        format.json { render :show, status: :created, location: @stage }
      else
        format.html { render :new }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stages/1
  # PATCH/PUT /stages/1.json
  def update
    respond_to do |format|
      if @stage.update(stage_params)
        format.html { redirect_to @stage, notice: 'Stage was successfully updated.' }
        format.json { render :show, status: :ok, location: @stage }
      else
        format.html { render :edit }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stages/1
  # DELETE /stages/1.json
  def destroy
    @stage.destroy
    respond_to do |format|
      format.html { redirect_to stages_url, notice: 'Stage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stage
      @stage = Stage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stage_params
      params.require(:stage).permit(:name)
    end
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/_form.html.erb
<%= form_with(model: stage, local: true) do |form| %>
  <% if stage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stage.errors.count, "error") %> prohibited this stage from being saved:</h2>

      <ul>
      <% stage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :stage_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stages/edit.html.erb
<h1>Editing Stage</h1>

<%= render 'form', stage: @stage %>

<%= link_to 'Show', @stage %> |
<%= link_to 'Back', stages_path %>

app/views/stages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stages.each do |stage| %>
      <tr>
        <td><%= stage.name %></td>
        <td><%= link_to 'Show', stage %></td>
        <td><%= link_to 'Edit', edit_stage_path(stage) %></td>
        <td><%= link_to 'Destroy', stage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stage', new_stage_path %>

app/views/stages/new.html.erb
<h1>New Stage</h1>

<%= render 'form', stage: @stage %>

<%= link_to 'Back', stages_path %>

app/views/stages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stage.name %>
</p>

<%= link_to 'Edit', edit_stage_path(@stage) %> |
<%= link_to 'Back', stages_path %>